### ISSUE TITLE
Add TypeScript paths

### ISSUE THREAD

**Issue by steinalex** [steinalex/stock-tracker#71]
This'll be much cleaner when (if) you add Typescript paths. You can clean it up to look like:
```ts
import { ActionWithPayload } from 'utils/actions';
```

_Originally posted by @Sharakai in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM0MzUyNjk3OQ==/comments/review_comment_

**Comment by BenGladman** [comment]
Copied from https://github.com/steinalex/stock-tracker/pull/65/files#r343539513 ...

You can also do this just by setting
```
"baseUrl": "src",
```
in tsconfig (i.e. no need to set up `paths` too). Then you can do imports from any dir under `src`. That's what they've done in the project I'm currently working on.
