### ISSUE TITLE
Change constants

### ISSUE THREAD

**Issue by steinalex** [steinalex/stock-tracker#82]
No need to do this way.
`export const UPDATE_STOCK_TICKER = "UPDATE_STOCK_TICKER"` will automatically do it for you

_Originally posted by @zhouyuhe in https://github.com/steinalex/stock-tracker/pull/81_

**Comment by steinalex** [comment]
@BenGladman @Sharakai is it better to infer (like the above example) or add a `typeof` (which I've done in my code). Or does this not make a difference?

**Comment by steinalex** [comment]
E.g.

`export const UPDATE_STOCK_TICKER = "UPDATE_STOCK_TICKER";`
`export type UPDATE_STOCK_TICKER = typeof UPDATE_STOCK_TICKER;`

**Comment by BenGladman** [comment]
I don't fully understand the question... Where do you use the type `export type UPDATE_STOCK_TICKER = typeof UPDATE_STOCK_TICKER;`? and what would you need to change to not use it?

**Comment by steinalex** [comment]
Sorry, to clarify:
Rather than creating each `constant` like this:
`export const UPDATE_STOCK_TICKER = "UPDATE_STOCK_TICKER";`
`export type UPDATE_STOCK_TICKER = typeof UPDATE_STOCK_TICKER;`

I could export the constants like this:
`export const UPDATE_STOCK_TICKER = "UPDATE_STOCK_TICKER"`

When I then create the action, specify it as `typeof` like this:
`export type UpdateCompanyOverviewAction = ActionWithPayload<`
  `typeof UPDATE_COMPANY_OVERVIEW,`
  `CompanyOverview`
`>;`

**Comment by BenGladman** [comment]
Aha.

Entirely up to your preference I think. I'd say if you only need to use that type once (when creating the action type) then using `typeof` there instead of exporting the type looks like less code, which is a bonus.

**Comment by steinalex** [comment]
Yeah that's a good point - will look into changing in a new PR then :)
